version: '2.3'

services:

  face-classifier:
    image: face-classifier
    container_name: face-classifier
    working_dir: /ekholabs/face-classifier
    build:
      context: ../
      dockerfile: docker/Dockerfile

    ports:
      - "8084:8084"

    volumes:
      - ../:/ekholabs/face-classifier
      - /media/enric/7c7b26fc-7eaf-4a2a-8ca5-33cfda8fe970/:/datasets
     
    command: python3 src/web/faces.py
